create table if not exists public.users (
  id bigint generated by default as identity primary key,
  open_id text not null unique,
  name text,
  email text,
  login_method text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title varchar(140) not null,
  category varchar(80) not null,
  description text not null,
  image_url text,
  project_url text,
  tags text not null,
  status text not null default 'draft' check (status in ('draft', 'published')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists projects_status_order_idx on public.projects (status, sort_order);
create index if not exists projects_sort_order_idx on public.projects (sort_order);

create table if not exists public.recovery_snapshots (
  id bigint generated by default as identity primary key,
  storage_key varchar(512) not null,
  checksum varchar(64) not null,
  record_count integer not null,
  created_at timestamptz not null default now()
);

create index if not exists recovery_snapshots_created_at_idx on public.recovery_snapshots (created_at desc);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at before update on public.projects for each row execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public.projects enable row level security;
alter table public.recovery_snapshots enable row level security;
